### ISSUE TITLE
Մուտքի կետի գեներացիա

### ISSUE THREAD

**Issue by armenbadal** [sargtigran/basic-ir#12]
Եթե ծրագրավորողը սահմանել է `Main` անունով ենթածրագիր, ապա IR-ում գեներացնել դրան կանչող `main()` ֆունկցիա։

**Comment by sargtigran** [comment]
Իսկ Բայսիկում կա՞ main֊ի գաղափար։

**Comment by armenbadal** [comment]
Չկա, բայց մենք ստիպված ենք մուտքի կետ ապահովել։ Ես նախատեսել եմ, որ `Main` անունով ենթածրագիրը լինի մուտքի կետ։ Իսկ IR-ում պիտի ապահովել դրա կանչը։

Իսկ եթե ծրագրավորողը սահմանի `main()` անունով ֆունկցիա։ (?)
